---
- name: Ensure all block devices are present
  assert:
    that:
      - item in ansible_devices
    fail_msg: Can't find block device /dev/{{ item }}
    quiet: true
  loop: "{{ raid_block_devs }}"

- name: Get mdraid device info
  command:
    cmd: mdadm --detail --scan
  register: mdraid_check
  changed_when: false

- name: VDO checks
  block:
    - name: Ensure raid_vdo_purpose is correctly set
      assert:
        that:
          - "'virtualization' in raid_vdo_purpose or 'object_storage' in raid_vdo_purpose"
        success_msg: "Using a {{ raid_vdo_multiplier }}x multiplier for VDO's logical volume size."
        fail_msg: "raid_vdo_purpose must be one of 'virtualization' or 'object_storage'"

    - name: Get existing VDO devices
      command: vdostats
      changed_when: false
      register: vdo_check
  when: raid_create_vdo|bool
