---
- name: Define options for mirrored RAID
  set_fact:
    lv_opts: --mirrors {{ raid_nummirrors }}
  when: raid_level == 'raid1'

- name: Define options for striped RAID
  set_fact:
    lv_opts: --stripes {{ raid_numstripes }}
  when: >
    raid_level == 'raid0' or
    raid_level == 'raid5' or
    raid_level == 'raid6'

- name: Define options for striped + mirrored RAID
  set_fact:
    lv_opts: --stripes {{ raid_numstripes }} --mirrors {{ raid_nummirrors }}
  when: raid_level == 'raid10'

- name: Set new raid_lv_name if using VDO
  set_fact:
    raid_lv_name: "{{ raid_name ~ '_vpool' }}"
  when: raid_create_vdo|bool

# NOTE: this also creates the PVs
- name: Create volume group {{ raid_vg_name }}
  lvg:
    state: present
    vg: "{{ raid_vg_name }}"
    vg_options: --dataalignment {{ raid_vg_dataalignment }}
    pvs: "/dev/disk/by-partlabel/{{ raid_partition_names|join(',/dev/disk/by-partlabel/') }}"

- name: Create RAID logical volume {{ raid_lv_name }}
  lvol:
    state: present
    active: true
    vg: "{{ raid_vg_name }}"
    lv: "{{ raid_lv_name }}"
    size: 100%FREE
    opts: --type {{ raid_level }} {{ lv_opts }}
    # 100%FREE makes lvol non-idempotent, so we must specify shrink=no
    shrink: no

- name: Refresh LVM facts
  setup:
    filter: ansible_lvm

- name: Set raid_device
  set_fact:
    raid_device: /dev/{{ raid_vg_name }}/{{ raid_lv_name }}

- name: Get size of lvmraid device
  set_fact:
    raid_size: "{{ (ansible_lvm.lvs[raid_lv_name].size_g ~ ' GB')|human_to_bytes }}"
