---
- name: Create mdraid array
  command: >
    mdadm
      --create
      --name={{ raid_name }}
      --level={{ raid_level[4:] }}
      --chunk={{ raid_chunksize }}
      --raid-devices={{ raid_block_devs|count }}
      /dev/md/{{ raid_name }}
      /dev/disk/by-partlabel/{{ raid_partition_names|join(' /dev/disk/by-partlabel/') }}
  when: ('/dev/md/' ~ raid_name) not in mdraid_check.stdout
  notify: refresh_device_facts

- name: Flush handlers
  meta: flush_handlers

- name: Set raid_device
  set_fact:
    raid_device: /dev/md/{{ raid_name }}

- name: Get real path of the mdraid device
  stat:
    path: "{{ raid_device }}"
  # We want the "stat.lnk_source" key
  register: real_path

- name: Create var for mdraid real_path
  set_fact:
    # Trimming "/dev/" from the mdraid device
    mdraid_device: "{{ real_path.stat.lnk_source[5:] }}"

- name: Get MD-UUID and size for mdraid device
  set_fact:
    # Trimming "md-uuid-"
    mdraid_md_uuid: "{{ ansible_devices[mdraid_device].links.ids[1][8:] }}"
    raid_size: "{{ ansible_devices[mdraid_device].size|human_to_bytes }}"
