---
- name: Set partition flag for lvmraid
  set_fact:
    parted_flag: lvm
  when: raid_backend == 'lvmraid'

- name: Partition bios-boot
  community.general.parted:
    state: present
    device: /dev/{{ item }}
    label: gpt
    number: 1
    name: "bios_boot_{{ idx }}"
    flags: [ "{{ parted_flag|default('raid') }}" ]
    part_end: 1M
  loop: "{{ raid_block_devs }}"
  loop_control:
    index_var: idx

- name: Partition raid
  community.general.parted:
    state: present
    device: /dev/{{ item }}
    label: gpt
    number: 1
    name: "{{ raid_name }}_member{{ idx }}"
    flags: [ "{{ parted_flag|default('raid') }}" ]
    part_start: 1M
    part_end: 98%
  loop: "{{ raid_block_devs }}"
  loop_control:
    index_var: idx
  register: raid_partitions

# Extracts partition names (raid_member{0,1,2...}) from the complex structure
# of the raid_partitions variable into a simple list
- name: Build a list of our partitions
  set_fact:
    raid_partition_names: "{{ raid_partition_names }} + [ '{{ item.invocation.module_args.name }}' ]"
  vars:
    raid_partition_names: []
  loop: "{{ raid_partitions.results }}"
