---
- name: Set partition flag for lvmraid
  set_fact:
    parted_flag: lvm
  when: raid_backend == 'lvmraid'

- name: Partition block devices
  parted:
    state: present
    device: /dev/{{ item }}
    label: gpt
    number: 1
    name: raid_member{{ idx }}
    flags: [ "{{ parted_flag|default('raid') }}" ]
  loop: "{{ raid_block_devs }}"
  loop_control:
    index_var: idx
  register: raid_partitions

# Extracts partition names (raid_member{1,2,3...}) from the complex structure
# of the raid_partitions variable into a simple list
- name: Build a list of our partitions
  set_fact:
    raid_partition_names: "{{ raid_partition_names }} + [ '{{ item.invocation.module_args.name }}' ]"
  vars:
    raid_partition_names: []
  loop: "{{ raid_partitions.results }}"
